version: 2
updates:

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "monthly"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"