name: Quality Gate
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
  push:
    branches:
      - master
      - dev
    paths:
      - "src/**/**.rs"
      - "tests/**/**.rs"

jobs:
  quality-gate:
    uses: RustLangES/.github/.github/workflows/quality-gate.yml@main
    with:
      runs-on: ubuntu-latest
      checks-command: "--all --check"
      clippy-command: "-- -D warnings"
      tests-command: "test"