name: test, analyze and publish

on:
    workflow_run:
        workflows: ["Quality Gate"]
        types:
            - completed
    workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: release ${{ matrix.target }}
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl]
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "README.md LICENSE-MIT"