name: test, analyze and publish

on:
    workflow_run:
        workflows: ["Quality Gate"]
        types:
            - completed
    workflow_dispatch:

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: cargo build --release
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: mks-binary
          path: target/release/mks
    
  release:
    uses: jd-apprentice/jd-workflows/.github/workflows/cliff.yml@main
    if: github.ref == 'refs/heads/master'
    with:
      binary_name: mks
      binary_path: ./target/release
      file_path: ./target/release/mks
      name: "generate a changelog"
      runs_on: ubuntu-latest
      cliff_args: "-vv --latest --strip header"
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}